repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
        exclude: ^(docs/.*|^frontend/.*)
      - id: end-of-file-fixer
        exclude: ^(docs/.*|^frontend/.*)
      - id: check-yaml
        exclude: ^(docs/.*|^frontend/.*)
      - id: check-added-large-files
        exclude: ^(docs/.*|^frontend/.*|bachelor-thesis-hutan-mihai.pdf)

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black-jupyter
        exclude: ^(docs/.*|^frontend/.*)
        language_version: python3.12.2
        args: [ --line-length=150 ]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^(docs/.*|^frontend/.*)
        name: isort (python)
        language_version: 3.12.2
        args: [ --profile=black, --line-length=150 ]
